### ISSUE TITLE
Is it  possible to match empty values?

### ISSUE THREAD

**Issue by RedRain77** [maforget/CRDataManager#3]
For example, If  I wanted to set the year a comic was published but only if the year was already missing.

I only recently found the updated version of this plugin, its amazing thank you.

**Comment by maforget** [comment]
Numerical Values default are -1, so to match an empty year you would check `Year IS -1` or `Year LESS 0`, etc. 

Note that the Number & AlternateNumber fields are considered strings so to check for an empty value of these it would be `AlternateNumber IS ''`.
