### ISSUE TITLE
Add custom value when processed

### ISSUE THREAD

**Issue by Fred-Vatin** [maforget/CRDataManager#4]
I would expect I can use this smart list. 
![image](https://github.com/maforget/CRDataManager/assets/22337329/7a05be9d-76f3-43f1-b6e0-e094957d5579)

But there is no custom value written by the plugin.
![image](https://github.com/maforget/CRDataManager/assets/22337329/c91e8d63-05e3-4b87-bfa2-cdef831c80b7)

**Comment by maforget** [comment]
First the DataManager.processed was only in v1. Also you wouldn't see it in the Custom tab, by default if a CustomValue has a `.` in the name, it will be hidden. A SmartList will still work though.

To show hidden custom values check inside `ComicRack.ini` for `ShowCustomScriptValues`.

Check the nightly 2.07.04.820, you will need to enable the option in the Setting Dialog before using it.

https://github.com/maforget/CRDataManager/releases/tag/nightly
