### ISSUE TITLE
DataManager not working when using the rule published greater

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [maforget/CRDataManager#7]
I tried a few times to switch from V1 to V2.
It was always not working and now i had time and found the problem.
I'm using on different rules the  <rule field="Published" modifier="Greater" value="2023/01/01"> in combination with the Series.
If this is used it will not work, if i delete the published rules it will do the work.

I'm using 2.07.05.828

**Comment by maforget** [comment]
What do you mean not working? You said it prevent you from going from v1 to v2, does it not import v1 rules? Or simply the rule isn't working correctly?

I've created a rule with Greater and Published in v1 and imported it in v2 and it imported correctly. The app still has the v1 code inside it to parse these file.

Can you share a .dat file?

**Comment by maforget** [comment]
I've found the issue fixed in ef80c63550379397ad0a16ed5fc6a9e3e924b68f.

Check new release 2.07.06.830 or nightly

**Comment by AlexanderTurnowsky** [comment]
Great thank you, yes this is fixed in the new Version.
